ln -snf /opt/java/bin/java /usr/bin/java
ln -snf /opt/java/bin/javac /usr/bin/javac
ln -snf /opt/java/bin/javah /usr/bin/javah
ln -snf /opt/java/bin/javaws /usr/bin/javaws
ln -snf /opt/java/bin/javadoc /usr/bin/javadoc
ln -snf /opt/java/bin/jps /usr/bin/jps
ln -snf /opt/java/bin/jar /usr/bin/jar
ln -snf /opt/java/bin/jdb /usr/bin/jdb
ln -snf /opt/java/bin/javap /usr/bin/javap
